<?php

/**
* Districts of Uzbekistan
* (uncounted-updated in 2021-september)
*
* Source:
 * - https://en.wikipedia.org/wiki/Districts_of_Uzbekistan
 *
 * @author  ibragimov ramazon(zekr@live.com)
 * @version 1.0.0
 * @license http://www.gnu.org/licenses/gpl-2.0.html
 */

global $places;
$places['UZ'] = array(
    'TASHKENT-CITY' => array(
        'Bektemir',
        'Chilonzor',
        'Yashnaobod',
        'Mirobod',
        'Mirzo Ulug\'bek',
        'Sergeli',
        'Shayxontoxur',
        'Olmazor',
        'Uchtepa',
        'Yakkasaroy',
        'Yunusobod',
        'Yangi Hayot',
        '* Другой район',
    ),
    'TASHKENT' => array(
        'Bekobod',
        'Bekobod shahri',
        'Bo\'stonliq',
        'Bo\'ka',
        'Chinoz',
        'Chirchiq shahri',
        'Nurafshon shahri',
        'Qibray',
        'Ohangaron tumani',
        'Angren shahri',
        'Ohangaron shahri',
        'Oqqo\'rg\'on',
        'Olmaliq shahri',
        'Parkent',
        'Piskent',
        'Quyi Chirchiq',
        'O\'rta Chirchiq',
        'Yuqori Chirchiq',
        'Yangiyo\'l tumani',
        'Yangiyo\'l shahri',
        'Zangiota',
    ),
    'ANDIJAN' => array(
        'Andijon tumani',
        'Andijon shahri',
        'Asaka',
        'Baliqchi',
        'Buloqboshi',
        'Bo\'ston',
        'Ulung\'or',
        'Paxtaobod',
        'Jalaquduq',
        'Izboskan',
        'Marhamat',
        'Oltinko\'l',
        'Xo\'jaobod',
        'Xonobod',
        'Shahrixon',
        'Qo\'rg\'ontepa',
    ),
    'FERGANA' => array(
        'Farg\'ona tumani',
        'Farg\'ona shahri',
        'Quva',
        'Marg\'ilon shahri',
        'Quvasoy shahri',
        'Toshloq',
        'Qo\'qon shahri',
        'Yozvon',
        'Qo\'shtepa',
        'Oltiariq',
        'Rishton',
        'Bag\'dod',
        'Buvayda',
        'Uchko\'prik',
        'Dang\'ara',
        'Furqat',
        'O\'zbekiston',
        'Beshariq',
        'So\'x',
    ),
    'NAMANGAN' => array(
        'Namangan shahri',
        'Mingbuloq',
        'Kosonsoy',
        'Namangan tumani',
        'Norin',
        'Pop',
        'To\'raqo\'rg\'on',
        'Uychi',
        'Uchqo\'rg\'on',
        'Chortoq',
        'Chust',
        'Yangiqo\'rg\'on',
    ),
    'SIRDARYO' => array(
        'Boyovut',
        'Guliston tumani',
        'Guliston shahri',
        'Yangiyer shahri',
        'Shirin shahri',
        'Sayxunobod',
        'Sirdaryo',
        'Mirzaobod',
        'Oqoltin',
        'Sardoba',
        'Xovos',
    ),
    'JIZZAKH' => array(
        'Arnasoy',
        'Baxmal',
        'Do\'stlik',
        'G\'allaorol',
        'Sharof Rashidov',
        'Zarbdor',
        'Zafarobod',
        'Zomin',
        'Paxtakor',
        'Mirzacho\'l',
        'Forish',
        'Yangiobod',
        'Jizzax shahri',
    ),
    'SURXONDARYO' => array(
        'Angor',
        'Bandixon',
        'Boysun',
        'Denov',
        'Jarqo\'rg\'on',
        'Qiziriq',
        'Qumqo\'rg\'on',
        'Muzrabot',
        'Oltinsoy',
        'Termez shahri',
        'Sariosiyo',
        'Sherobod',
        'Sho\'rchi',
        'Termiz tumani',
        'Uzun',
    ),
    'QASHQADARYO' => array(
        'Qarshi shahri',
        'G\'uzor',
        'Dehqonobod',
        'Qamashi',
        'Qarshi tumani',
        'Kasbi',
        'Kitob',
        'Koson',
        'Mirishkor',
        'Muborak',
        'Nishon',
        'Shahrisabz tumani',
        'Shahrisabz shahri',
        'Chiroqchi',
        'Yakkabog\'',
    ),
    'SAMARQAND' => array(
        'Samarqand shahri',
        'Jomboy',
        'Narpay',
        'Payariq',
        'Samarqand tumani',
        'Qo\'shrabot',
        'Kattaqo\'rg\'on tumani',
        'Kattaqo\'rg\'on shahri',
        'Ishtixon',
        'Nurobod',
        'Pastdarg\'om',
        'Toyloq',
        'Bulung\'ur',
        'Oqdaryo',
        'Paxtachi',
        'Urgut',
    ),
    'BUKHARA' => array(
        'Buxoro shahri',
        'Olot',
        'Buxoro tumani',
        'G\'ijduvon',
        'Jondor',
        'Kogon',
        'Qorako\'l',
        'Qorovulbozor',
        'Peshku',
        'Romitan',
        'Shofirkon',
        'Vobkent',
    ),
    'NAVOIY' => array(
        'Navoiy shahri',
        'Navoiy tumani',
        'Konimex',
        'Qiziltepa',
        'Xatirchi',
        'Navbaxor',
        'Nurota',
        'Tomdi',
        'Uchquduq',
        'Zarafshon shahri',
    ),
    'XORAZM' => array(
        'Urganch shahri',
        'Urganch tumani',
        'Bog\'ot',
        'Gurlan',
        'Qo\'shko\'pir',
        'Hazorasp',
        'Tuproq qal\'a',
        'Xiva shahri',
        'Xiva tumani',
        'Xonqa',
        'Shovot',
        'Yangiariq',
        'Yangibozor',
    ),
    'KARAKALPAKSTAN' => array(
        'Nukus shahri',
        'Nukus tumani',
        'Amudaryo',
        'Beruniy',
        'Qorao\'zek',
        'Kegeyli',
        'Bo\'ztau',
        'Qo\'ng\'irot',
        'Qonliko\'l',
        'Mo\'ynoq',
        'Taxtako\'pir',
        'To\'rtko\'l',
        'Xo\'jayli',
        'Taxiatosh',
        'Chimboy',
        'Sho\'manay',
        'Ellikqal\'a',
    ),
);

// Use this filter to handle the Districts of Uzbekistan
$places['UZ'] = apply_filters('scpwoo_custom_places_uz', $places['UZ']);
